services:
    migrate:
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        container_name: laravel-migrate
        command: php artisan migrate --force
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
        volumes:
            - .:/var/www
        networks:
            - episode-duplicator-network

    app:
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        container_name: episode-duplicator
        restart: unless-stopped
        depends_on:
            migrate:
                condition: service_completed_successfully
        volumes:
            - .:/var/www
        networks:
            - episode-duplicator-network

    worker:
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        container_name: laravel-worker
        command: php artisan queue:work --timeout=3600
        restart: unless-stopped
        depends_on:
            migrate:
                condition: service_completed_successfully
        volumes:
            - .:/var/www
        networks:
            - episode-duplicator-network

    postgres:
        image: postgres:15.0-alpine
        container_name: postgres-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            interval: 3s
            timeout: 3s
            retries: 10
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - episode-duplicator-network

    redis:
        image: redis:alpine
        container_name: redis-server
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
        networks:
            - episode-duplicator-network

    nginx:
        image: nginx:alpine-slim
        container_name: app-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - episode-duplicator-network
        depends_on:
            - app

networks:
    episode-duplicator-network:
        driver: bridge

volumes:
    pgdata: ~
    redisdata: ~
