FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN docker-php-ext-install pdo_pgsql pgsql mbstring exif pcntl bcmath gd

RUN pecl install redis xdebug && docker-php-ext-enable redis xdebug

COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer


RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

WORKDIR /var/www

EXPOSE 9000

CMD ["php-fpm"]
