<?php

declare(strict_types=1);

namespace App\Helper;

final class LogEvent
{
    public const string DUPLICATION_SCHEDULED = 'EPISODE_DUPLICATION_SCHEDULED';

    public const string DUPLICATION_COMPLETED = 'EPISODE_DUPLICATION_COMPLETED';

    public const string DUPLICATION_FAILED = 'EPISODE_DUPLICATION_FAILED';

    public const string DUPLICATION_CANCELLED = 'EPISODE_DUPLICATION_CANCELLED';

    public const string DUPLICATION_IN_PROGRESS = 'DUPLICATION_IN_PROGRESS';

    public const string DUPLICATION_NOT_FOUND = 'DUPLICATION_NOT_FOUND';

    public const string DUPLICATE_EPISODE_STARTED = 'DUPLICATE_EPISODE_JOB_STARTED';

    public const string DUPLICATE_EPISODE_COMPLETED = 'DUPLICATE_EPISODE_JOB_COMPLETED';

    public const string DUPLICATE_EPISODE_CANCELLED = 'DUPLICATE_EPISODE_JOB_CANCELLED';

    public const string DUPLICATE_PART_STARTED = 'DUPLICATE_PART_JOB_STARTED';

    public const string DUPLICATE_PART_COMPLETED = 'DUPLICATE_PART_JOB_COMPLETED';

    public const string DUPLICATE_PART_CANCELLED = 'DUPLICATE_PART_JOB_CANCELLED';

    public const string CLEANUP_STARTED = 'CLEANUP_EPISODE_STARTED';

    public const string CLEANUP_COMPLETED = 'CLEANUP_EPISODE_COMPLETED';

    public const string CLEANUP_FAILED = 'CLEANUP_EPISODE_FAILED';
}
